### ISSUE TITLE
Mellanrum d och funktion

### ISSUE THREAD

**Issue by KristofferC** [Micket/chalmers#2]
Är det meningen att ha `\:` i derivatorna här: https://github.com/Micket/chalmers/blob/master/contmech.sty#L78

Det ger ett stort mellanrum mellan d:et och funktionen.

![image](https://cloud.githubusercontent.com/assets/1282691/8333757/bb4e845e-1a94-11e5-9beb-e9cb23d3320f.png)

**Comment by Micket** [comment]
Det var ett avsiktligt mellanrum, men det kanske är lite stort.

**Comment by vikahl** [comment]
\newcommand*\dif{\mathop{}\!\mathrm{d}} verkar ofta vara det föreslagna sättet.
http://tex.stackexchange.com/questions/60545/should-i-mathrm-the-d-in-my-integrals

**Comment by Micket** [comment]
Fast det du länkar är en integral? Om något, dra ihop nämnaren?
